INCLUDE_PATH="-I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/"
LIBRARIES="-m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o"


nvcc $INCLUDE_PATH $LIBRARIES dydt.cu.o dydt.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/gpu_memory.cu.o examples/pyJac/out/release/gpu_memory.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/jacob.cu.o examples/pyJac/out/release/jacob.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/mass_mole.cu.o examples/pyJac/out/release/mass_mole.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/mechanism.cu.o examples/pyJac/out/release/mechanism.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/rxn_rates.cu.o examples/pyJac/out/release/rxn_rates.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/rxn_rates_pres_mod.cu.o examples/pyJac/out/release/rxn_rates_pres_mod.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/sparse_multiplier.cu.o examples/pyJac/out/release/sparse_multiplier.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -dc -o examples/pyJac/out/release/spec_rates.cu.o examples/pyJac/out/release/spec_rates.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o generic/radau2a/release/complexInverse.cu.o generic/radau2a/release/complexInverse.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o generic/radau2a/release/inverse.cu.o generic/radau2a/release/inverse.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o generic/radau2a/release/read_initial_conditions.cu.o generic/radau2a/release/read_initial_conditions.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o generic/radau2a/release/solver_generic.cu.o generic/radau2a/release/solver_generic.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o generic/radau2a/release/solver_main.cu.o generic/radau2a/release/solver_main.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o radau2a/release/radau2a.cu.o radau2a/release/radau2a.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o radau2a/release/radau2a_init.cu.o radau2a/release/radau2a_init.cu

nvcc -I/usr/local/cuda/samples/common/inc -I/usr/local/cuda/include -I/home/kwoksun2/accelerInt/generic -I/home/kwoksun2/accelerInt/examples/pyJac/out/ -I/home/kwoksun2/accelerInt/radau2a -m64 -Xptxas -v -arch=sm_30 -O3 -maxrregcount 63 -Xcompiler -fopenmp --ftz=false --prec-div=true --prec-sqrt=true --fmad=false -DRADAU2A -dc -o radau2a/release/radau2a_props.cu.o radau2a/release/radau2a_props.cu

nvcc examples/pyJac/out/release/chem_utils.cu.o examples/pyJac/out/release/dydt.cu.o examples/pyJac/out/release/gpu_memory.cu.o examples/pyJac/out/release/jacob.cu.o examples/pyJac/out/release/mass_mole.cu.o examples/pyJac/out/release/mechanism.cu.o examples/pyJac/out/release/rxn_rates.cu.o examples/pyJac/out/release/rxn_rates_pres_mod.cu.o examples/pyJac/out/release/sparse_multiplier.cu.o examples/pyJac/out/release/spec_rates.cu.o generic/radau2a/release/complexInverse.cu.o generic/radau2a/release/inverse.cu.o generic/radau2a/release/read_initial_conditions.cu.o generic/radau2a/release/solver_generic.cu.o generic/radau2a/release/solver_main.cu.o radau2a/release/radau2a.cu.o radau2a/release/radau2a_init.cu.o radau2a/release/radau2a_props.cu.o -L/usr/local/cuda/samples/common/lib/linux/x86_64//linux -L/usr/local/cuda/lib64 -lstdc++ -lcuda -lcudart -dlink -o radau2a-int-gpu_dlink.o

gcc -fPIC -fopenmp -Xlinker -rpath /usr/local/cuda/lib64 examples/pyJac/out/release/chem_utils.cu.o examples/pyJac/out/release/dydt.cu.o examples/pyJac/out/release/gpu_memory.cu.o examples/pyJac/out/release/jacob.cu.o examples/pyJac/out/release/mass_mole.cu.o examples/pyJac/out/release/mechanism.cu.o examples/pyJac/out/release/rxn_rates.cu.o examples/pyJac/out/release/rxn_rates_pres_mod.cu.o examples/pyJac/out/release/sparse_multiplier.cu.o examples/pyJac/out/release/spec_rates.cu.o generic/radau2a/release/complexInverse.cu.o generic/radau2a/release/inverse.cu.o generic/radau2a/release/read_initial_conditions.cu.o generic/radau2a/release/solver_generic.cu.o generic/radau2a/release/solver_main.cu.o radau2a/release/radau2a.cu.o radau2a/release/radau2a_init.cu.o radau2a/release/radau2a_props.cu.o radau2a-int-gpu_dlink.o -L/usr/local/cuda/samples/common/lib/linux/x86_64//linux -L/usr/local/cuda/lib64 -lstdc++ -lcuda -lcudart -L/opt/intel/compilers_and_libraries_2016.2.181/linux/mkl/lib/intel64 -lm -lmkl_rt -lmkl_intel_lp64 -lmkl_core -lmkl_gnu_thread -ldl -lmkl_mc -lmkl_def -o radau2a-int-gpu
