#!/bin/bash 

# declare a name for this job to be sample_job
#PBS -N shaerd_radau2a_nvprof 

#PBS -k o
#PBS -j oe

# request 1 node
#PBS -l nodes=1:ppn=1:gpus=1
# request 4 hours and 30 minutes of cpu time
#PBS -l walltime=00:30:00        
# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m bea
# specify your email address
#PBS -M kwoksun2@illinois.edu
# By default, PBS scripts execute in your home directory, not the 
# directory from which they were submitted. The following line 
# places you in the directory from which the job was submitted.  
cd $PBS_O_WORKDIR
make clean
make test
rm *.prof
# run the program
./test
nvprof -f -o shared_timeline.prof ./test 
nvprof --kernels "intDriver" --analysis-metrics -f -o shared_analysis.prof ./test 
cuda-memcheck ./test
